version: "3.8"
services:
  blog_api_db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    container_name: blog_api_db
  
  blog_api:
    build: 
      context: .
      dockerfile: ./dockerfile.dev
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    volumes:
      - .:/app
    depends_on: 
      - blog_api_db
    container_name: blog_api
